name: Update Android and iOS dependencies
on:
  workflow_dispatch:
    inputs:
      updateAndroid:
        description: 'update Android dependencies?'
        default: 1
      updateiOS:
        description: 'update iOS dependencies?'
        default: 1
      triggerTests:
        description: 'trigger tests on PR?'
        default: 1
      baseBranch:
        description: 'create the new branch from this base'
        default: 'main'

env:
  branchPrefix: "workflow/auto-update-deps-"

jobs:
  update_dependencies:
    name: update-deps
    runs-on: ubuntu-latest
    steps:
      - name: Check out base branch
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.baseBranch }}
          
      - name: Create new branch
        run: git checkout -b ${{env.branchPrefix}}${{github.run_number}}

      - name:  Run Android update script
        if: ${{ github.event.inputs.updateAndroid }}
        run: 
      # Run iOS update script.
      # Push branch (force push if necessary).
      # Create PR from that branch.
      # As firebase-workflow-trigger, label the PR to trigger integration tests.

