name: Update Android and iOS dependencies (placeholder)
on:
  workflow_dispatch:
    inputs:

jobs:
  update_dependencies:
    name: update-dependencies
    runs-on: ubuntu-latest
    steps:
      name: Placeholder step
      run: true

