name: Update Android and iOS dependencies
on:
  workflow_dispatch:
    inputs:
      updateAndroid:
        description: 'update Android dependencies?'
        default: 1
      updateiOS:
        description: 'update iOS dependencies?'
        default: 1
      triggerTests:
        description: 'trigger tests on PR?'
        default: 1
      baseBranch:
        description: 'create the new branch from this base'
        default: 'main'

env:
  branchPrefix: "workflow/auto-update-deps-"
  triggerTestsLabel: "tests-requested: quick"

jobs:
  update_dependencies:
    name: update-deps
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Check out base branch
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.baseBranch }}

      - name: Install prerequisites
        run: |
          python scripts/gha/install_prereqs_desktop.py
          python -m pip install requests
          
      - name: Name new branch
        run: |
          echo "NEW_BRANCH=${{env.branchPrefix}}${{github.run_number}}" >> $GITHUB_ENV
      - name: Create new branch
        run: |
          git remote update
          git checkout -b "${NEW_BRANCH}"

      - name: Run Android update script
        if: ${{ github.event.inputs.updateAndroid }}
        run: |
          python scripts/update_android_ios_dependencies.py --skip_ios

      - name: Run iOS update script
        if: ${{ github.event.inputs.updateiOS }}
        run: |
          python scripts/update_android_ios_dependencies.py --skip_android
          # Update Firestore external version to match Firestore Cocoapod version.
          firestore_version=$(grep "pod 'Firebase/Firestore'" ios_pod/Podfile | sed "s/.*'\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\)'.*/\1/")
          sed -i~ "s/^set(version [^)]*)/set(version CocoaPods-${firestore_version})/i" cmake/external/firestore.cmake
          
      - name: Push branch if there are changes
        id: push-branch
        if: ${{ github.event.inputs.updateiOS || github.event.inputs.updateAndroid }}
        run: |
          if git update-index --refresh; then
            echo "::set-output name=branch_changed::0"
            echo "BRANCH_CHANGED=0" >> $GITHUB_ENV
          else
            echo "::set-output name=branch_changed::1"
            echo "BRANCH_CHANGED=1" >> $GITHUB_ENV
            git diff
            git push --set-upstream origin "${NEW_BRANCH}"
          fi

      - name: Create pull request on branch
        if: steps.push-branch.branch_changed
        run: |
          python scripts/gha/create_pull_request.py --token ${{github.token}} --head "${NEW_BRANCH}" --base "${{ github.event.inputs.baseBranch }}" --title "Update dependencies"

      - name: Get token for triggering tests as firebase-workflow-trigger
        uses: tibdex/github-app-token@v1
        if: ${{ github.event.inputs.triggerTests && steps.push-branch.branch_changed }}
        id: generate-token
        with:
          app_id: ${{ secrets.WORKFLOW_TRIGGER_APP_ID }}
          private_key: ${{ secrets.WORKFLOW_TRIGGER_APP_PRIVATE_KEY }}

      - name: Set test trigger label.
        if: ${{ github.event.inputs.triggerTests && steps.push-branch.branch_changed }}
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          label: "${{ env.triggerTestsLabel }}"
          type: add
